spring.application.name=cadastro


spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

app.jwt.expiration-seconds=900

app.jwt.private-key=classpath:keys/private.pem
app.jwt.public-key=classpath:keys/public.pem

pluggy.base-url=https://api.pluggy.ai
pluggy.client-id=10484b18-ca75-43f7-b4d5-ec8bcc387be2
pluggy.client-secret=df1249fa-23fc-48da-bf37-5ac834cccd91
pluggy.oauth-redirect-url=http://localhost:4200/pluggy/callback
pluggy.include-sandbox=true


